### ISSUE TITLE
Sharing view should allow for downloading the whole folder on mobile

### ISSUE THREAD

**Issue by moritzheiber** [cozy/cozy-drive#1041]
I tested this yesterday, but it would appear the share UI doesn't allow for whoever uses the link to access the share to download the folder:
![9eec95cc-57e9-48e3-b77c-e868da321cdd](https://user-images.githubusercontent.com/616813/42501134-529213ca-8433-11e8-8722-c3549f249269.jpeg)
As you can see, the menu at the top is missing entirely. Also, the handles next to the files are non-functional.

I would love to have the same abilities on mobile as I have with the desktop client:
![screenshot_2018-07-10 cozy-drive](https://user-images.githubusercontent.com/616813/42501269-abd7d488-8433-11e8-8726-2834f5985e5d.png)

**Comment by jsilvestre** [comment]
Hey @moritzheiber 

Sorry for not answering sooner, the tab was open but I forgot. I add it to our backlog so we can fix this. Thanks for reporting it!

Regards,
Joseph.

**Comment by Crash--** [comment]
Almost 2 years later...

I'm closing this issue since it seems to be fixed. 
<img width="738" alt="Capture d’écran 2020-02-07 à 08 26 48" src="https://user-images.githubusercontent.com/1107936/74009544-b6860000-4983-11ea-8b4c-5b7a6fcdc485.png">
