### ISSUE TITLE
"Photos backup - uptodate" should not appear when the feature is disabled

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-drive#1125]
I don't want to sync my photos so I disabled the feature. Nonetheless a ribbon appears telling me that the synchronization is up-to-date:

![screenshot_20180823-001048](https://user-images.githubusercontent.com/3419050/44516927-a9f5e500-a6c6-11e8-8364-5de89ef69cda.png)

**Comment by goldoraf** [comment]
I'm on it :smile:

**Comment by goldoraf** [comment]
Fixed here: https://github.com/cozy/cozy-drive/pull/1126/commits/f57733d4504bb8ae6643a626c4a53cd767b5da3b
