### ISSUE TITLE
current folder - contextual menu

### ISSUE THREAD

**Issue by Claiw** [cozy/cozy-drive#1150]
Hi, 

I would like to UI-optimize this menu : 
<img width="362" alt="screen shot 2018-09-10 at 16 30 08" src="https://user-images.githubusercontent.com/31621610/45303751-cee7b600-b516-11e8-9120-d4865a9d8b1b.png">

you can find the precise specs here : https://zpl.io/VYB75zw
to summarize : 
- space between your contextual menu and its button is 0.25 rem
- we are supposed to have a regular vertical spacing between the menu elements
- the icons color is supposed to be --slate-grey, not --charcoal-grey
<img width="500" alt="screen shot 2018-09-10 at 16 41 08" src="https://user-images.githubusercontent.com/31621610/45304410-58e44e80-b518-11e8-8480-b124d57edfcc.png">

Thank you,
Claire

**Comment by GoOz** [comment]
Waiting to know if we're using the Menu component from Material-UI or not before changing anything and coding for nothing.

**Comment by Crash--** [comment]
@GoOz I think we can do the work now. Not sure if we will use M-UI. Even if we do it, we do not know when. 

Will rise this issue to our meeting ;)
