### ISSUE TITLE
cozy-drive autostart not working on Arch Linux

### ISSUE THREAD

**Issue by Krytexo** [cozy/cozy-drive#1285]
### Summary 
Enabling the auto-start feature does not work on Arch Linux. It starts an empty electron app instead. 

### Environment
Arch Linux vanilla + Deepin DE
```bash
$ uname -r
4.19.2-arch1-1-ARCH
$ pacman -Qe |grep cozy
cozy-desktop 3.10.2-1
```

### Hacking my way around
Activating the auto-start feature seems only to add the file `~/.config/autostart/electron.desktop` so I disabled the feature and added the file `cozy-desktop.desktop` myself. It seems to work as expected now.

### Expected behavior
Obviously, the desktop file should be Cozy's one and not electron.

**Comment by clochix** [comment]
Hello @Krytexo ,

thanks for reporting :-) 

We know there are some issues with auto-start on GNU/Linux, but we have other priorities for the moment.

To report such issues, please use [our forum](https://https://forum.cozy.io). Github is only used by our development team, so if you report an issue here, I may not be aware of it;
