### ISSUE TITLE
[Feature] publicly shared files downloadable via wget

### ISSUE THREAD

**Issue by Wenzel** [cozy/cozy-drive#1307]
Hi,

this is a feature request,

When i share a file via a public link to someone, i would like them to be able to download the file without going to the Cozy web interface and click on download.

Dropbox implemented this mechanism by using a parameter `&dl=0`, in their public URLs
If you switch the parameter to `1`, you can download the file directly:
https://superuser.com/a/486351/270168

It would be great if Cozy implemented this feature too.

Thanks !

**Comment by clochix** [comment]
Hello @Wenzel ,

You’re right, that would be useful :-) 
Added to or XMas wishlist.

(for the record, our [forum](https://forum.cozy.io) is better suited for this kind of features requests.)
