### ISSUE TITLE
Make logs more compact

### ISSUE THREAD

**Issue by melsophos** [cozy/cozy-drive#1750]
The size of the log files in my ~/.cozy-desktop grew up to 2.2 Go in 8 days (after clean install). Since this is quite big, I would suggest to find an alternative representation of the logs instead of plain json (for example adding a gz compression?).

I am using the version 3.13.4 on Linux (Fedora 29).

**Comment by y-lohse** [comment]
Hi, i re-created your issue on the correct repo over [here](https://github.com/cozy-labs/cozy-desktop/issues/1649). This repo is for the web version of drive :)

**Comment by melsophos** [comment]
Thanks, sorry for the confusion!
