### ISSUE TITLE
Corrupted file on either side

### ISSUE THREAD

**Issue by flo-dhalluin** [cozy/cozy-drive#1797]
When I start the desktop app, the sync fails with the following error message ( in a console ): 
```
(node:12596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: File is corrupt on either side (md5sum matches but size does not)

```
I don't know how to get more info, and this prevents me from syncing at all. 

Let me know if I can provide more details.

**Comment by y-lohse** [comment]
Hi, this is the repo for the web and mobile apps. i've recreated your issue in the desktop app over [here](https://github.com/cozy-labs/cozy-desktop/issues/1698).
