### ISSUE TITLE
Move MenuAwareMobile to UI 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-drive#1859]
This component should be part of UI 

https://github.com/cozy/cozy-drive/blob/master/src/components/Menu/Menuawaremobile.jsx#L31

See https://github.com/cozy/cozy-ui/pull/1186

**Comment by ptbrowne** [comment]
I know you opened the issue not to forget, but when you have the time, can you edit the description to indicate what is the need for this component ?

**Comment by Crash--** [comment]
I'm closing this issue since @y-lohse is working on bringing a responsive ActionMenu to UI. (https://github.com/cozy/cozy-ui/pull/1347) This was the goal of this issue
