### ISSUE TITLE
File is not synchronized

### ISSUE THREAD

**Issue by PascalLeMerrer** [cozy/cozy-drive#1893]
A modified file in the local cozy drive directory is not published towards my drive.
The windows explorer says the file was last modified 2 hours ago.
However I don't get its last version on my second computer, even after a manuel synchro.

Cozy client says it was modified/synchronized 9 days ago on one computer and 8 days ago on the other.
Triggering a manual synchronization on the computer hosting the modified version of the file has no effect

The file is a the root of my cozy drive directory.

**Comment by ptbrowne** [comment]
Ping @taratatach :)

**Comment by taratatach** [comment]
Hi @PascalLeMerrer,

this repository is about the Web version of Cozy Drive. The desktop version's repository is hosted at https://github.com/cozy-labs/cozy-desktop.

On a side note, github issues are not the best place to receive support for Cozy Desktop and I encourage you to contact support via the app itself (`Preferences` tab > `Send us a message`). Run time logs will be attached to your message and will greatly help us understand the issue you're facing and thus provide better support to you.

**Comment by Crash--** [comment]
I close this issue since this is not related to Drive web.

If you still need action from our side, do hesitate to send us a message from the desktop app
