### ISSUE TITLE
`UIWebView` deprecation

### ISSUE THREAD

**Issue by florentmorin** [cozy/cozy-drive#1933]
`UIWebView` component is deprecated since years. 

And will no longer be accepted to App Store by the end of 2020.

Now, you need to use `WKWebView`.

Source: https://developer.apple.com/news/?id=12232019b

**Comment by Crash--** [comment]
Thanks @florentmorin. We already done a few works this past year to start the migration. We still have a few issues to close and we hope that the end of life of `UIWebview` will force Apple to fix some radars ;).

**Comment by Crash--** [comment]
Closing this issue since Apple still accept UIWebView for now.
