### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by JVariance** [cozy/cozy-drive#2131]
Hi, I translated most of Cozy's projects into german on transifex a while ago already. When can I expect the translations to arrive in the apps?

**Comment by Crash--** [comment]
Hello @JVariance ! 

Thank you for your work. Let me see with the product team to see if we have enough translation to let the user chose it. 

In the meantime I think we can set your cozy in german to have your feedbacks (and see if we forgot to build our apps with your translations). If you're interested in, you can email Claude at claude@cozycloud.cc

**Comment by JVariance** [comment]
> Hello @JVariance ! 
> 
> Thank you for your work. Let me see with the product team to see if we have enough translation to let the user chose it. 
> 
> In the meantime I think we can set your cozy in german to have your feedbacks (and see if we forgot to build our apps with your translations). If you're interested in, you can email Claude at claude@cozycloud.cc 

Thanks, I mailed Claude 👍
