### ISSUE TITLE
Invalid meta data errors should not stop sync

### ISSUE THREAD

**Issue by DavidLibeau** [cozy/cozy-drive#2310]
I am using Cozy with heavily updated files (i.e. Latex documents or Zotero files). I often having an "Invalid meta data error" for these files and I am forced to click on the button "Try again" in order to have my files updated (even my other files that don't have this error). I would like my files to be synch and have some kind of automatic retry for the ones that have this meta data error.

<img width="440" alt="Capture d’écran 2021-04-12 à 10 41 34" src="https://user-images.githubusercontent.com/11574966/114367870-2a6dfa80-9b7d-11eb-8638-53f1e27e9e3d.png">

**Comment by taratatach** [comment]
Hi @DavidLibeau,

there is already an automatic retry when the client encounters this error. The delay for this error is 1 minute. If you're not done modifying your file or can wait for 1 minute before your latest changes are synced with your Cozy I would suggest leaving the client do its job in the background.

**Comment by DavidLibeau** [comment]
I have to click on the "Retry" button. The 1 minute retry seems not to work as I noticed several times, and made this observation right know again, that files modified several hours ago are update after I clicked on the "Retry" button, and not automatically.

**Comment by taratatach** [comment]
OK. You can send us a message via the app's Preferences tab. It will contain log files that we can analyze and find out what's happening.

**Comment by Crash--** [comment]
I'm closing this issue since it's related to cozy-desktop https://github.com/cozy-labs/cozy-desktop/ . Feel free to contact us if there is still an issue.
