### ISSUE TITLE
Cozy Drive hanging on macOS Big Sur

### ISSUE THREAD

**Issue by edouardroger** [cozy/cozy-drive#2334]
Sur MacOS 11.3.1, Cozy Drive (v. 3.27.0) je suis régulièrement amené à forcer l'application à quitter lors de l'extinction de mon ordinateur.

Dans le détail, Cozy Drive est ouvert au démarrage et demeure de manière active dans le dock alors qu'auparavant il y apparaissait mais comme une application inactive (i.e. sans pastille noire en dessous de l'application), puis, lorsque que ferme la session, je suis quasiment toujours contraint de forcer l'application à quitter pour y parvenir.

Je ne sais pas si ça un rapport mais, à toutes fins utiles, un extrait d'un fichier figurant dans DiagnosticReports :

Process:               Cozy Drive Helper [484]
Path:                  /Applications/Cozy Drive.app/Contents/Frameworks/Cozy Drive Helper.app/Contents/MacOS/Cozy Drive Helper
Identifier:            Cozy Drive Helper
Version:               3.27.0
Code Type:             X86-64 (Native)
Parent Process:        Cozy Drive [440]
Responsible:           Cozy Drive [440]
User ID:               501

Date/Time:             2021-05-11 20:54:15.090 +0200
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Anonymous UUID:        00F30E77-A097-415C-B284-E0414F7A7A51

Sleep/Wake UUID:       46782946-0647-4025-88A2-61DBF28B4B87

Time Awake Since Boot: 15000 seconds
Time Since Wake:       20 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Chrome_ChildIOThread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [484]

**Comment by Crash--** [comment]
Salut, 

Je ne sais pas comment je suis passé à côté de cette issue et je m'en excuse. Est-ce toujours d'actualité malgré les dernières versions ? (ici c'est le repo de Drive web, drive desktop étant là-bas https://github.com/cozy-labs/cozy-desktop)

**Comment by edouardroger** [comment]
Bonjour,
Merci pour cette réponse et désolé pour l’erreur de dépôt ! :-)
Ce n’est plus d’actualité, merci.
