### ISSUE TITLE
Allow multiple selections while uploading media to Cozy Drive on mobile apps

### ISSUE THREAD

**Issue by Sbruk** [cozy/cozy-drive#2400]
Hello,

It would be great if it was possible to select, for instance, multiple photos during a file upload selection in the Cozy mobile applications instead of having to open the "Upload a file..." menu for each photo.

Thanks in advance!

**Comment by Crash--** [comment]
Yeah I agreed. It already works on iOS, but we have to upgrade Cordova to make it works on Android. (cf https://github.com/apache/cordova-android/commit/42c0cba7f7ad037cb0b7254a7102408e9b868087) 

Will make a new try soon

**Comment by Crash--** [comment]
Should be fixed by https://github.com/cozy/cozy-drive/commit/a21449f591e18c6d973fb6aa0d18b08612dd71c5 

Will be released pretty soon
