### ISSUE TITLE
Blurry delete modal

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-drive#259]
![image](https://cloud.githubusercontent.com/assets/465582/26277491/10873fa6-3d89-11e7-8c63-93889ce96c54.png)

**Comment by GoOz** [comment]
@ptbrowne Did you see that blur only with that modal on that app? Or is it with every modal?

**Comment by ptbrowne** [comment]
Yes, I only saw this bug with this modal. Good luck with this one 😅

Maybe it was a temporary bug of Chrome. I'll tell you if I see it again.

**Comment by enguerran** [comment]
Check it on others browsers. I am sure the code cannot  be responsible for things like this, at least without specific css rules.

**Comment by ptbrowne** [comment]
Did not see it for a long time
