### ISSUE TITLE
Can't select text in text/PDF files preview

### ISSUE THREAD

**Issue by whiver** [cozy/cozy-drive#2673]
Hi team,

The preview of a **text** or **pdf** file in the Cozy webapp does not allow selecting anything, meaning that we need to download the file and open it with another file reader to copy any data inside, which is annoying.

Thanks! :)

**Comment by Crash--** [comment]
Hi @whiver, thanks for taking the time to create an issue. I juste created a fix on cozy UI's component in order to fix the issue on desktop. Let's see what others have to say about it. I'll ping you when released in drive.

**Comment by whiver** [comment]
Thanks for your quick answer @Crash--, that's super cool :)

**Comment by Crash--** [comment]
Should be released now. Forgot to update this issue.
