### ISSUE TITLE
Can't connect to my Cozy

### ISSUE THREAD

**Issue by mlcdf** [cozy/cozy-drive#282]
Hello,

I have a Cozy at https://maximelcdf.cozycloud.cc and I can access it via my browser or the old Cozy Android app, but when I try with the Cozy Drive app, I get this error:

![screenshot_20170607-101249](https://user-images.githubusercontent.com/9364931/26868634-fda67b1a-4b69-11e7-87ff-33ba3751b72e.png)

Did I miss anything?

**Comment by jsilvestre** [comment]
Hello @mlcdf, and thank you for the report.

The new version of the app is only compatible with the next version of Cozy Cloud, currently called "v3". It is a complete rewrite, and will be available during the month. We plan on adding a specific message so you are not mislead, sorry about that!

Regards,
Joseph.

**Comment by mlcdf** [comment]
Oh okay.

Well thank your answer!
