### ISSUE TITLE
Question: does Cozy work with rclone?

### ISSUE THREAD

**Issue by vindarel** [cozy/cozy-drive#2864]
Hi everyone,

Happy user of Cozy Cloud here. I also use [rclone](https://rclone.org/) for backups, to another cloud provider, and I'd like to use Cozy (I'd prefer to pay Cozy for extra space than the other big one).

I couldn't find a clue wether they would work together. Do they?

rclone works for

> [many cloud providers] FTP HTTP SFTP local filesystem …

> [rclone providers], built on standard protocols such as WebDAV or S3, […] work out of the box.

The way to start a configuration is to run

    rclone config

and to choose the provider, but Cozy isn't in the list, so I don't know how I'd proceed if it appears it works out of the box.

Thanks.

**Comment by clochix** [comment]
Hello @vindarel,

Please don't use Issues for support requests.

You can ask you questions [on out forum](https://forum.cozy.io/c/francais/5) or send an email to support at cozycloud.cc.

A brief anwser: it is not possible for now to use rclone to backup your data into your Cozy. Cozy does not support any of the common file transfer protocols, but uses it's own API.

rclone and Cozy are both open source projects, so adding a Cozy provider to rclone using [our File API](https://github.com/cozy/cozy-stack/blob/master/docs/files.md) would be possible, but would require some work, and it's not on our roadmap.

**Comment by vindarel** [comment]
Got it. Thanks, sorry for the noise.
