### ISSUE TITLE
Dot in folder name are interpreted as extensions

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-drive#339]
![image](https://user-images.githubusercontent.com/1580287/28672611-7f97606a-72e0-11e7-8c71-376a37605181.png)

**Comment by GoOz** [comment]
@aenario this bug has been fixed already, probably not deployed in production though. 
See https://github.com/cozy/cozy-drive/commit/7f23150ff39148dc2cd8b5e5f039ecd98d55fc59

**Comment by enguerran** [comment]
@GoOz are you sure? Because the commit is dated a month.

BTW, the commit contains a debug `console.log` at https://github.com/cozy/cozy-drive/commit/7f23150ff39148dc2cd8b5e5f039ecd98d55fc59#diff-7e3f754a65a763e426e5b54107d0702aR147

**Comment by GoOz** [comment]
@enguerran Yes, almost 100% sure, I can't reproduce on local & recette but I can on my personal Cozy V3. 
But the thing is that giving the code I don't see how this could still happen. Folders are not even parsed anymore.

Also the `console.log` has been removed in another commit after that one.

**Comment by GoOz** [comment]
Should be deployed next monday.
