### ISSUE TITLE
Build time of css file

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-drive#421]
I worked on a problem with stylus, webpack and their loaders.

### a custom webpack.config.js

To have a clear view of what is happening, I created a custom simplified webpack config file with the following content:

```js
const path = require('path')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { DefinePlugin, optimize, LoaderOptionsPlugin } = require('webpack')
const PostCSSAssetsPlugin = require('postcss-assets-webpack-plugin')

/**
 * loaders:
 * - babel-loader
 * - json-loader
 * - style-loader
 * - css-loader
 * - postcss-loader
 * - stylus-loader
 *
 * plugins:
 * - extract-text-webpack-plugin
 *
 * lib:
 * - preact-compat
 * - cozy-ui
 * - autoprefixer
 */

module.exports = production => ({
  entry: path.resolve(__dirname, 'targets/drive/web/main.jsx'),
  // entry: path.resolve(__dirname, 'entry.js'),
  // entry: path.resolve(__dirname, 'src/temp.js'),
  output: {
    path: path.resolve(__dirname, 'build/drive'),
    filename: '[name].[hash].js'
  },
  resolve: {
    extensions: ['.js', '.jsx', '.styl'],
    alias: {
      react: 'preact-compat',
      'react-dom': 'preact-compat'
    },
    modules: [
      'node_modules',
      path.resolve(__dirname, 'src/lib'),
      path.resolve(__dirname, 'src')
    ]
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.jsx?$/,
        include: /node_modules\/cozy-ui/,
        loader: 'babel-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.styl$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader'
              // options: {
              //   sourceMap: false,
              //   importLoaders: 1,
              //   modules: true,
              //   localIdentName: '[local]--[hash:base64:5]'
              // }
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: false,
                plugins: () => [
                  require('autoprefixer')({
                    browsers: ['last 2 versions']
                  })
                ]
              }
            },
            {
              loader: 'stylus-loader',
              options: {
                // import: ['~normalize.css/normalize.css', '~cozy-ui']
              }
            }
          ]
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin('[name].noduplicate.css'),
    new optimize.UglifyJsPlugin({
      mangle: true,
      compress: {
        warnings: false
      }
    }),
    new DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production'), // to compile on production mode (redux)
      __DEVELOPMENT__: false,
      __DEVTOOLS__: false,
      __STACK_ASSETS__: true,
      __PIWIK_SITEID__: 8,
      __PIWIK_SITEID_MOBILE__: 12,
      __PIWIK_DIMENSION_ID_APP__: 1,
      __PIWIK_TRACKER_URL__: JSON.stringify('https://piwik.cozycloud.cc')
    }),
    new PostCSSAssetsPlugin({
      test: /\.css$/,
      plugins: [
        //     require('css-mqpacker'),
        require('postcss-discard-duplicates')
        //     require('postcss-discard-empty')
        //   ].concat(
        //     require('csswring')({
        //       preservehacks: true,
        //       removeallcomments: true
        //     })
        //   )
      ]
    })
  ]
})
``` 

This file contains some specific line to create a css file at the end of the build:

#### create the css file

```js
new ExtractTextPlugin('[name].noduplicate.css'),
```

#### remove duplicates

```js
new PostCSSAssetsPlugin({
  require('postcss-discard-duplicates')
})
```

#### what to put in the css file (aka loaders)

```js
{
  test: /\.styl$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader'
      },
      {
        loader: 'postcss-loader',
        options: {
          sourceMap: false,
          plugins: () => [
            require('autoprefixer')({
              browsers: ['last 2 versions']
            })
          ]
        }
      },
      {
        loader: 'stylus-loader'
      }
    ]
  })
}
```

To explain: starting at the `entry` file declared in the webpack config file, each time it sees something that matches `/\.styl$/` it uses `stylus-loader`, then `postcss-loader`, then `css-loader`

### How Webpack works

Once loaders did their jobs, plugins can do their. In the case of the `postcss-discard-duplicates`, it removes from the built css file duplicate codes.

### Observations

If I remove the `postcss-discard-duplicates` plugin, then, I got this result:

![](https://i.imgur.com/1V0OL30.png)

34 seconds to create a 1.27 MB css file.

If I remove duplicates, then:

![](https://i.imgur.com/tr0Egjn.png)

34 secondes to create a 282 kB css file.

Notice the following line:

```
Start PostCSSAssetsPlugin
Processing main.noduplicate.css...
Processed main.noduplicate.css. Length before: 1265860, length after: 282325
Finish PostCSSAssetsPlugin
``` 

The big version contains a lot of duplicates:

![](https://i.imgur.com/Un65Alg.gif)

### Analyses

Assuming there is no need to use `postcss-discard-duplicates` unless to correct developer's air-head, I __believe__ we could create a 300 kB file on a one-shot build. But how?

We use `.styl` files from `cozy-ui` instead of importing a unique `.css` file. Is that the best way?

We use `@require` in local `.styl` files to access some variables (values and `@extend`). With webpack and stylus-loader, we can `@require` non local files by adding `~` (tilde) character to tell webpack to look for the file in `node_modules`. Is that the best way?

I believe we don't need to import `.styl` files from `cozy-ui`. What we want to import are:

- styled react components
- themes
- css variables

Then we could create an `index.html` with the `<link href="themes.css" rel="stylesheet">`, use whatever technology to create local stylesheet using css variables and using styled react components in our own components.

I know there is some incoming [The Plan](https://github.com/cozy/cozy-ui/issues/195) and I would like to have some discussion to make _The Plan_ a usable, used and useful plan. What do **you** think?

**Comment by enguerran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Réparer cozy-ui pour utiliser la v4 dans Drive](https://trello.com/c/Jldls4LA/535-r%C3%A9parer-cozy-ui-pour-utiliser-la-v4-dans-drive)

**Comment by y-lohse** [comment]
I didn't have time to test any of this locally, but from what I understand:

- When importing components from cozy-ui, everything is fine and there's no duplicate css being created
- We should not import all of cozy-ui. Usually I create a single file I can import; it only contains mixins and variables and and produces no output at all. That's generally enough.
- We now have utility classes (for margins for example). These should be made available globally somehow, so that we can use them directly in our components. Like `cozy-mobile` at the moment.

**Comment by ptbrowne** [comment]
I started to work on this on Bank.

My results are there : https://gitlab.cozycloud.cc/labs/cozy-bank/merge_requests/126?deleted_source_branch=true

Before the `postcss-remove-duplicates` pass we were at 40Mo of CSS (🤢), now it is 1.5Mo. It is still very large and I will continue to investigate.

The main problem for us was the use of `require 'cozy-ui'` (thinking it was only imported once) instead of requiring only what we needed.

> We should not import all of cozy-ui. Usually I create a single file I can import; it only contains mixins and variables and produces no output at all. That's generally enough.

Personally, I prefer to be explicit on what I need. Use of global variables is not a good idea to me.

> We now have utility classes (for margins for example). These should be made available globally somehow, so that we can use them directly in our components.

For the `palette.styl`, I made an exception since cozy-ui, particularly $button and $forms placeholders, makes the assumption that it is available everywhere. [I used the `import` option of `stylus-loader` to have it imported automatically](https://gitlab.cozycloud.cc/labs/cozy-bank/commit/60b3cf8f5575056da4226b68feb83d3a9fc64a79). I would still prefer to have it explicitly imported.

**Comment by enguerran** [comment]
![](https://i.imgur.com/WbAq7xf.png)

**Comment by ptbrowne** [comment]
Amen

**Comment by y-lohse** [comment]
My points were:

1. Let's never `import`/`require`things in stylus that output css, unless super special cases. Importing things individually is explicit and good, but if it turns out we always require the same things it's useless overhead.
2. As I've mentioned before, I think this is bad:

```js
import componentStyles from `component.styl`

const Component = () => (
   <div className={componentStyles['my-component']}></div>
)
```

```stylus
import 'margins.styl'
import 'colors.styl'

.my-component
  margin: $margin-2;
  color: $my-blue;
  //more standard rules
```

This is better:

```js
const Component = () => (
   <div className='margin-2 my-blue ...more standard classes'></div>
)
```

Arguably, the reduced code makes it more explicit too, there's no `.my-component` abstraction that needs to be looked up. The implication is there is a set of standard classes available globally. Like a standard library in any language.  
Also, it's easier to use for outside contributors.

(If a component needs special styling that can't be achieved with the standard classes, then it should have a dedicated class. But that should not be the norm.)

**Comment by ptbrowne** [comment]
+9000, I completely agree :)

> The implication is there is a set of standard classes available globally.

I agree that it is a common thing for CSS and I am in favor of that. I was not in favor of that in the case of having things magically imported in the CSS.

**Comment by y-lohse** [comment]
> I was not in favor of that in the case of having things magically imported in the stylus files.

And I agree on that as well :) All good then !

**Comment by GoOz** [comment]
> Arguably, the reduced code makes it more explicit too, there's no .my-component abstraction that needs to be looked up. The implication is there is a set of standard classes available globally. Like a standard library in any language.
Also, it's easier to use for outside contributors.

Not so sure about that actually. This makes things way more complicate to build UI for us or outside contributors. I'm not saying there shouldn't be some classes like that, that's what I called "utility classes", but I'm not in favor of building UIs only with utility classes. I think this should be built as components. Utility classes should be here only as snippets to deal with details, not with the core of the components. That's the way I see it at least. :|

But I feel we're going out of the scope of this issue. This discussion should be in [The Plan](https://github.com/cozy/cozy-ui/issues/195)

**Comment by enguerran** [comment]
The issue is still open, here the next action to take:

- [ ] fix webpack build (especially for stylus and cozy-ui)
- [ ] migrate to create-cozy-app

**Comment by y-lohse** [comment]
I think the first item has actually been addressed, no? I haven't measured anything but it feels like the build times have gone down since the latest version of cozy-ui. But maybe it's just an impression.

**Comment by GoOz** [comment]
@y-lohse It's better, but I guess it could be even better. :)
