### ISSUE TITLE
Plan : Test + Publication de redux-cozy-client sur npm

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-drive#427]
## Test

Pour les tests, je vous propose que Travis lance les tests seulement si un fichier contenu dans src/lib/redux-cozy-client` a été modifié.

## Publication

Nous allons devoir publier la librairie sur npm (en mode automatique j'espère), je me dis autant mettre ça en place dès maintenant même si la librairie n'est pas encore stable. Nous utiliserons la nomentlature *semver*.

Prérequis : Il va falloir que l'on ajoute un fichier package.json dans le dossier de la lib.

Je vois plusieurs solutions : 

1. On publie à la main ...

2. A chaque modification Travis publie une nouvelle version automatiquement sur npm. Comment on gère les numéros de version ? ... beta-42 ?

3. A chaque modification du numéro de version Travis publie sur npm (il faut qu'il vérifie sur npm quelle version il y a actuellement et si la version n'existe pas il publie)

4. Travis push automatiquement le code sur un autre repo (cozy/redux-cozy-client). Ce qui permet d'avoir la documentation, les issues sur un autre repo que cozy-drive. Depuis ce nouveau repo on a juste a créer une release à la main pour que celui-ci publie sur npm (ou on met en place la release automatique quand le numéro de version change). Ca peut permettre de minimiser le temps d'execution coté Travis.

Vous en pensez quoi ?

## Tâche

- [x] Renommer la librairie (cozy-client) https://github.com/cozy/cozy-drive/commit/4e5e8f4d3dc8d54db53b0d1b6f8171c9ba4b7185
- [x] [Mettre en place une documentation](https://github.com/cozy/cozy-drive/blob/master/src/lib/cozy-client/README.md)
- [x] Ajouter un package.json (fix by https://github.com/cozy/cozy-drive/pull/435)
- [x] Publier sur npm à la main (https://www.npmjs.com/package/cozy-client)

## En plus quand on a le temps

- [ ] Tester la librairie seulement si une modification est faite
- [ ] Publier sur npm automatiquement après changement du numéro de version
- [ ] Ajouter un CHANGELOG.md
- [ ] Compiler la librairie

**Comment by ptbrowne** [comment]
I am not familiar with neither npm publishing nor travis testing but I think https://github.com/lerna/lerna could be useful here.

**Comment by enguerran** [comment]
@kosssi il faudrait ajouter une liste de tâches sur ton post avec une des tâches qui serait de renommer la bibliothèque.

Je ne sais pas ce qu'à prévu @goldoraf comme timing pour documenter et publier la biblio, mais il m'est avis qu'il faudrait utiliser semver si on a l'ambition d'avoir des _releases_ publiques (ie. utilisées par des tiers).

**Comment by ptbrowne** [comment]
+1 pour semver :)

**Comment by CPatchane** [comment]
I would add some new points to existing ones:

- Add all cozy-client dependencies in`package.json`
- Have PouchDB as `optionalDependencies` and use offline parts only if PouchDB is installed on application side

Since `cozy-client` is functional intented to be used in many applications, is not a good moment to use a specific repo for it?

**Comment by y-lohse** [comment]
> Since cozy-client is working and intented to be used in many applications, is it not a good moment to use a specific repo for it?

I think the criteria for this is stability. A separate repo doesn't change much in terms of what we can do regarding automation and publication, but it makes it a lot more painful to update. As long as it's undergoing frequent changes (and I think it still is), it's probably better to keep it here.

> Have PouchDB as optionalDependencies and use offline parts only if PouchDB is installed on application side

We can do this only if every app ships it's own copy of `cozy-client`. But if `cozy-client` replaces `cozy-client-js` and is served by the stack to avoid the overhead in every app, then it needs to be fully standalone and integrate redux, pouch, and whatever other dependency it has.

1. Option A) Every app has to compile and ship `cozy-client` and has an overhead of the size of `cozy-client` without deps (~150kb).
2. Option B) The stack serves a standalone copy of `cozy-client` and we have an overhead of ~200kb (pouch + redux + other `cozy-client` deps) on the first app load (then the file is served from the browser cache). And it's only overhead for the apps that don't use pouch, which will become less frequent.

So IMO, we should absolutely ship pouch with `cozy-client`.

**Comment by CPatchane** [comment]
> @y-lohse So IMO, we should absolutely ship pouch with cozy-client.

Very good point, since we ship `cozy-client-js` with the stack to keep a client as compatible as possible with the stack version (and this is very important), I don't see any other solution than embedding PouchDB then :/

**Comment by enguerran** [comment]
Everything was discussed? I close the issue.

Do not hesitate to reopen it if you want to add something about.
