### ISSUE TITLE
Impossible de récupérer l'url des applications depuis cozy-client

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-drive#469]
Lors que l'on récupère les documents du doctype `io.cozy.apps` avec `fetchCollection` ils ne contiennent pas le champ `links` généré par cozy-stack.

Du coup on est obligé de passer par cozy-client-js pour faire une requête sur /apps.

J'ai l'impression que c'est pas top

**Comment by goldoraf** [comment]
On peut maintenant récupérer la liste des apps depuis cozy-client.
