### ISSUE TITLE
Possibility to choose the images folder to upload

### ISSUE THREAD

**Issue by foxmask** [cozy/cozy-drive#537]
Hi,
Actually, I've most of 5Go of photos on Google Photos so they won't be able to enter on Cozy Drive all together.
Could it be possible to allow us to choose the images folder we want to upload from the settings of our account ?
Regards

**Comment by jsilvestre** [comment]
Hi @foxmask,

That is something we can consider, yes. I add your request to our tracking system so we make sure we don't forget to let you know if we work on it!

Regards,
Joseph.
