### ISSUE TITLE
[cozy-client] Choose the adapter used in fetchCollection

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-drive#555]
We have a performance card (https://trello.com/c/mBQdYuzZ/418-3-fetcher-les-donn%C3%A9es-via-un-fetchcollection-cozy-client-et-activer-la-synchronisation-en-parall%C3%A8le) to fix the long syncing time at the app startup. We want to display informations before the sync is finished.

We thought of issuing a fetchCollection and tell it to use the stack adapter for the first call :  `fetchCollection('transactions', 'io.cozy.bank.transactions', { adapter: 'stack' })`

Does it seem OK to you to add this parameter ? I can do the PR :)

**Comment by goldoraf** [comment]
What I have in mind in the future is to implement some kind of a `fetchPolicy`, à la Apollo : https://www.apollographql.com/docs/react/basics/queries.html

But as a temporary measure (the back still need to implement the `_bulk_docs` route to make the initial sync faster), I'm OK with your proposition.

**Comment by ptbrowne** [comment]
I see, I will try to keep this in mind for my PR.

**Comment by ptbrowne** [comment]
> the back still need to implement the _bulk_docs route to make the initial sync faster

I thought it was done ? https://github.com/cozy/cozy-stack/blob/52ae2a5868e52b7cc1a00a3c6ad16775d92bea5a/web/data/replication.go#L186
