### ISSUE TITLE
Share mobile Authentication ducks

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-drive#592]
Je dois faire en sorte que l'application Cozy Drive et Cozy Bank partagent le composant `Authentication` pour permettre une mutualisation du composant et ainsi qu'il puisse être facilement réutilisé dans d'autres applications.

# Information

Voici le composant [coté Drive](https://github.com/cozy/cozy-drive/tree/b11f543b84c2ed5191ebaaa08d5de92c2eb0c03f/src/authentication), [coté Bank](https://gitlab.cozycloud.cc/labs/cozy-bank/tree/d715dcf149fe36dcb28a6c40e370ce9652ecfe47/src/ducks/authentication).

Il contient:
- des composants reacts (Authenticate, SelectServer, Welcome, Revoke)
- une partie routeur permettant d'ajouter une route pour l'authentification ou pour la révocation.
- des traductions
- des composants cozy-ui
- des appels à la stack avec cozy-client-js
- une ouverture de la fenêtre de la stack avec cordova

# Les obstacles

## Les traductions

On devra créer un projet dans transifex pour permettre la traduction à un seul endroit.

## La gestion du routeur

Si on intègres la partie routeur cela veut dire que le composant est lié à react-router v3. 

# Solution proposé

Je me vois mal mettre ce composant dans cozy-ui. Je verrai plus la création d'une librairie contenant des composants fonctionnels de cozy.

Voici les différentes étapes que je vois:
- [ ] Trouver un nom à la librairie
- [ ] Création d'un dossier spécifique dans `cozy-drive/src/libs` ou créer un projet séparé ?
- [ ] Copier/Coller le composant `src/authentications`
- [ ] Créer un package.json avec les dépendances
- [ ] Mettre en place un build Travis pour builder le composant
- [ ] Tester le composant
- [ ] Créer un projet dans transifex
- [ ] Configurer les traductions
- [ ] Ajouter les traductions
- [ ] Importer la version dans cozy-drive + supprimer `src/authentication`
- [ ] Importer la version dans cozy-bank + supprimer `src/ducks/authentication`

**Comment by enguerran** [comment]
À mon sens c'est une application complète qui permet de configurer une app cozy standalone (ie. non servie par la stack et donc non liée de facto à un serveur).

Dans le monde android, on appelle ça une activité, non ?

**Comment by ptbrowne** [comment]
> Je me vois mal mettre ce composant dans cozy-ui

Pourquoi pas ?

> une partie routeur permettant d'ajouter une route pour l'authentification ou pour la révocation.

Est ce qu'on a vraiment besoin de la partie routeur ? Ca oblige à avoir un `MobileRouter` et un `Router` et ca couple ce composant/activité à react-router. Est ce qu'on pourrait pas se débrouiller sans ?

**Comment by enguerran** [comment]
On peut se débrouiller sans `react-router`, sans `redux` et faire uniquement un composant wrapper : https://blog.ticabri.com/2017/12/11/redux-vs-fullstate/

On doit même pouvoir se débrouiller sans transifex (et laisser le wording sous la responsabilité des apps utilisant ce code).

Et finalement avoir un joli composant qui peut être instancié au besoin par une app.

**Comment by ptbrowne** [comment]
Ca pose le problème d'avoir un process pour décider quand quelque chose doit rejoindre Cozy UI. Une ébauche de process : 

1. Est ce que ce sera utilisé par plusieurs applications ? Oui
2. Est ce que c'est un composant graphique ? Oui
3. Est ce que ce sera utile à la communauté ? Oui
4. Est ce qu'il y a plusieurs vues, besoin d'un routeur ? Nous sommes en train d'y réfléchir mais j'ai l'impression que c'est pas nécessaire

**Comment by goldoraf** [comment]
Je plussoie @ptbrowne, surtout pas de router là-dedans, on n'en a pas besoin. D'ailleurs des modifs ont déjà été faites en ce sens par @y-lohse récemment, et le `MobileRouter` (dont on devrait changer le nom d'ailleurs) se comporte maintenant comme un [simple composant wrapper du vrai router](https://github.com/cozy/cozy-drive/blob/master/src/authentication/MobileRouter.jsx). Ce module d'authent doit faire la même chose : proposer un wrapper à mettre en composant root de son app, et qui si l'user n'est pas authentifié, affiche l'onboarding, sinon affiche ses enfants (j'espère que je suis clair, sinon ne pas hésiter à me demander).

De plus, ce module (c'est plus qu'un composant) n'a rien à faire dans cozy-ui : je propose que, tel le viewer, on en fasse un module à la racine de `/src`, avec son package.json pour pouvoir l'utiliser en dep npm. 

@kosssi @enguerran @ptbrowne ok pour vous ? je suis assez clair ?

**Comment by enguerran** [comment]
Je ne sais pas ce que le responsable de cozy-ui a conclu de https://github.com/cozy/cozy-ui/issues/195 mais je ne crois pas que la place d'application/activité soit dans cozy-ui, même dans la partie composant fonctionnel (qui pour moi sont des composants comme des grid, des datepickers, etc. des trucs simples quoi).

Je suis [ok pour la version wrapper](https://github.com/cozy/cozy-drive/issues/592#issuecomment-351090307).

Quant à l'endroit qui héberge ses fichiers, je n'ai pas de préférences.

Pour ce qui est des traductions, je propose que ce module se comporte comme s'il était en anglais par défaut, sauf si on lui file des clés de traduction. Pour ne pas forcer les gens à avoir un compte transifex s'ils veulent utiliser ce module.

**Comment by ptbrowne** [comment]
Je me met à la place d'un développeur d'application Cozy. Déjà pour l'instant je dois installer 3 libs (cozy-ui et cozy-client) pour pouvoir travailler. Et là je devrais encore installer une troisième lib ?

**Comment by enguerran** [comment]
> c'est limite trop simple pour être une app

pourquoi une app ne pourrait pas être simple ?

> trop complexe pour être un composant UI

c'est surtout que ce n'est pas un composant d'interface utilisateur.

**Comment by enguerran** [comment]
> Je me met à la place d'un développeur d'application Cozy. Déjà pour l'instant je dois installer 3 libs (cozy-ui et cozy-client) pour pouvoir travailler. Et là je devrais encore installer une troisième lib ?

Non, tu ne dois pas installer une 3e lib, tu peux faire ton formulaire comme tu l'entends. Mais si tu ne veux pas, tu peux utiliser _l'app d'onboarding_ (appelée ici _module d'authent_).

**Comment by goldoraf** [comment]
> Je me met à la place d'un développeur d'application Cozy. Déjà pour l'instant je dois installer 3 libs (cozy-ui et cozy-client) pour pouvoir travailler. Et là je devrais encore installer une troisième lib ?

En même temps, tu as vu le nb de libs de babel ;) ? Blague à part, ça ne me choque pas plus que ça qu'il faille installer une 3ème lib, d'autant plus que c'est uniquement dans le cas d'une app mobile, ce qui ne concerne pas tout le monde.

> C'est très clair, à part sur le fait que "ca n'ait rien à faire dans cozy-ui". Ca me semble pas du tout clair.

cozy-ui doit rester une lib de composants d'UI "dumb". Là, il ne s'agit pas d'un composant simple mais bien d'un module qui fait pas mal de choses quand même. C'est mieux ?

**Comment by ptbrowne** [comment]
> cozy-ui doit rester une lib de composants d'UI "dumb"

C'est là le coeur de la question.  Cozy-ui pour moi doit regrouper des composants qui soient utiles, composables, qui nous servent à nous et à la communauté. Je vois pas trop pourquoi on se limiterait à des composants très simples. Pour l'instant j'ai pas eu de vraies raisons sur pourquoi on mettrait pas ça dans `cozy-ui`.

**Comment by ptbrowne** [comment]
Plusieurs fois dans cette discussion on a parlé de choses "simples" ou de faire "pas mal de choses".

Dans ma tête, en me mettant à la place d'un développeur utilisant ce composant, pour moi il ne fait fonctionellement qu'une chose, permettre à l'utilisateur de se connecter à son Cozy. Si pour ça il a besoin de faire des choses compliquées, ca n'est pas pour ca que je le considère comme "non simple".

Donc pour moi, un module/composant peut rejoindre Cozy UI lorsqu'il permet de faire une seule chose et de la faire bien. Comme vous l'avez compris, je pense que ce composant/module remplit cette condition :) .

**Comment by kosssi** [comment]
ok pour la partie routeur, je pensais dans tous les cas partir des derniers changements sur cozy-drive ;)

Pour le choix du dépôt, ma réflexion était:
- pour la gestion de mes datas : cozy-client
- pour la gestion des designs : cozy-ui
- pour la gestion de composants plus complexe : intents, authentification ... une autre librairie.

Pour les traductions j'aurai vraiment voulu les gérer au même endroit que le composant. Pour avoir qu'une seul fois la traduction pour l'ensemble des applications. Ce qui permet d'avoir un wording non gérer par l'application elle même.
Voir comme l'indique @enguerran que ça soit paramétrable.

**Comment by goldoraf** [comment]
@ptbrowne c'est plus qu'un composant d'UI parce qu'il y a un flow, du code "métier", c'est de l'UX et non de l'UI, c'est pas juste une dropdown. Si tu trouves potentiellement confusant pour un dev de devoir installer plusieurs libs, pour moi c'est pire d'avoir à boire et à manger dans une seule lib. cozy-ui, c'est notre react-toolbox : n'incluons pas dedans des modules applicatifs.

**Comment by y-lohse** [comment]
Yo !

🚗  Pour le routeur, je suis d'accord avec l'accord général : pas besoin de routeur.

📚 Pour le dépôt, comme beaucoup, ca me semblait "trop gros" pour être dans cozy-ui… mais je suis sensible aux arguments de @ptbrowne . Je ne trouve pas en toute bonne foi de critère qui permettrais de l'exclure de UI, donc… va pour ca.

💬 Pour les traductions:

1. Soit les textes du composant sont configurables (genre via des props), et dans ce cas ok pour qu'elles ne soient pas inclus dedans.
2. Soit les textes sont built-in, et dans ce cas les traductions aussi.

L'option 2 me parait bien meilleure, ca serait dommage de mutualiser le composant mais de devoir dupliquer les trads. Ca implique d'apprendre à combiner plusieurs fichiers de traductions. C'est pas très drôle mais ca nous serait utiles dans d'autres cadres aussi.

**Comment by ptbrowne** [comment]
Pour info, je compte le mettre d'abord dans Cozy UI, ca me paraît être beaucoup moins de travail que de créer un nouveau repo et il me semble qu'il n'y a pas d'avantages à le séparer du moins pour le moment. Ce sera de toute manière facile de l'extraire si on découvre que sa place n'est pas dans Cozy UI.

**Comment by goldoraf** [comment]
@ptbrowne je ne suis pas du tout d'accord avec ça. Il n'y a pas besoin d'un autre repo, c'est bien pour ça que j'essaie de pousser le monorepo de Drive : arrêtons de considérer qu'il faut un repo à part pour publier une lib !!! D'autre part, le code a déjà été "extrait" dans son propre duck dans le repo de Drive : `src/authentication`. Je ne vois pas pourquoi il devrait aller ailleurs, et je ne veux pas qu'on balance des pavés comme ça dans cozy-ui. Merci de ta compréhension.

**Comment by Crash--** [comment]
Bon au final ce composant à eu sa lib à part dans cozy-libs. Beau débat 👏
