### ISSUE TITLE
[cozy-client] all doctypes are deleted if files doctype is present in DataAccessFacade

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-drive#662]
While working on https://github.com/cozy/cozy-drive/pull/661, I saw that there is the following test in [`DataAccessFacade::setup`](https://github.com/drazik/cozy-drive/blob/34af758e94a465700242bcbd82a97cc922a79254/src/lib/cozy-client/DataAccessFacade.js#L32) : 

```js
offline: hasFilesDoctype ? { doctypes: [FILES_DOCTYPE] } : offline
```

The effect is that if I have an array containing X doctypes, including the files doctype, all the others are simply deleted and we only pass the files doctype to `cozy.client.init`.

Is it really the wanted behaviour ? Or could it be a bug ?

**Comment by goldoraf** [comment]
C'est effectivement le comportement recherché. A l'origine, la gestion de PouchDB fût implémentée dans `cozy-client-js` pour Drive mobile, mais "activée" uniquement pour le doctype `io.cozy.files`. Pour Bank, nous avions besoin de synchroniser plus de doctypes et nous avons choisi de mettre cette gestion de PouchDB dans `cozy-client`, qui était déjà utilisé par Bank. Mais Drive mobile ne l'utilisant pas encore, il fallait conserver la gestion du doctype `io.cozy.files` dans `cozy-client-js`, tout du moins en attendant que Drive soit porté vers `cozy-client`. Le code mentionné permet de faire cela : laisser `cozy-client` gérer tous les doctypes SAUF les fichiers.
