### ISSUE TITLE
Cozy drive error on install on Linux Mint 17.1 Rebecca: GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by notafish** [cozy/cozy-drive#667]
Hello. I just installed Cozy Drive on my computer and get this error: 

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.5xq5aV): unable to import leveldown

Cozy drive has gone through the set up, installed apparently well, but does not seem to want to sync with my computer (I threw one image in there and it didn't sync.).

**Comment by y-lohse** [comment]
Hello @notafish !

Correct me if I'm wrong, but you're talking about the cozy app for desktop, and not the web app — in which case the repo you're looking for is here : https://github.com/cozy-labs/cozy-desktop

**Comment by aenario** [comment]
Hello @notafish I am one of the developer for the cozy-drive for desktop application. 

Thanks for the report, we are aware of this problem and are working to fix it. You can follow the current status of our progress in the following PR : https://github.com/cozy-labs/cozy-desktop/pull/905. Could you let us know which Linux distribution and version you use there?

Thanks, 
Romain

**Comment by y-lohse** [comment]
I'm closing this issue since it's tracked elsewhere :)
