### ISSUE TITLE
Invalid Web App Manifest

### ISSUE THREAD

**Issue by benfrancis** [cozy/cozy-drive#686]
I'm using the the cloud instance at mycozy.cloud and when I try to add the web app to my home screen it doesn't open in standalone display mode as specified in the manifest.

Firefox Nightly doesn't show the ambient add to home screen badge in the URL bar and adding a page shortcut fails to find an icon. Chrome finds an icon but has to automatically generate a name and doesn't open the app in standalone display mode.

I noticed that the "name" field of the web app manifest for the photos app is blank, which may be the reason.

**Comment by benfrancis** [comment]
Cozy Collect's manifest has a name field (although Chrome doesn't seem to use it), but Cozy Drive doesn't. None of them open in standalone display mode.

**Comment by goldoraf** [comment]
Thanks for taking the time to fill an issue, it's greatly appreciated! The manifest files we have right now are custom-made for apps deployment on the server side, we need to adapt them a bit so that our apps could be added to home screens.

**Comment by Crash--** [comment]
Should be fixed, closing this issue.
