### ISSUE TITLE
[cozy-client] Updates only the first FETCH_LIMIT documents

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-drive#707]
## Problem

When deleting a large number of documents (> 50), only the first 50 documents are deleted.

## Expected

All documents matching the query should be deleted.

## Explanation

Since `deleteDocuments` uses `queryDocuments` under the hood and `queryDocuments` is limiting the fetch by `FETCH_LIMIT`, only the first `FETCH_LIMIT` documents are updated (deleted in this case). A possible solution would be for `queryDocuments` to support `{ limit: null }` in its options and then it would fetch all the documents. Then `updateDocuments` could add `{ limit: null }` to queryDocuments options .

`queryDocuments`

https://github.com/cozy/cozy-drive/blob/0e4fd3d033725aece96d8fd63a3fcf5a0d680310/src/lib/cozy-client/adapters/CozyStackAdapter.js#L40-L78

`updateDocuments`

https://github.com/cozy/cozy-drive/blob/0e4fd3d033725aece96d8fd63a3fcf5a0d680310/src/lib/cozy-client/adapters/CozyStackAdapter.js#L104-L112

`deleteDocuments`

https://github.com/cozy/cozy-drive/blob/0e4fd3d033725aece96d8fd63a3fcf5a0d680310/src/lib/cozy-client/adapters/CozyStackAdapter.js#L120-L125

## Extra

Could there be a way of not having to request all documents to delete them ? The stack should be involved in this case.

**Comment by Crash--** [comment]
@ptbrowne Should we close also this one? :)

**Comment by ptbrowne** [comment]
Yep.
