### ISSUE TITLE
Missing interface on GNU/Linux

### ISSUE THREAD

**Issue by hleroy** [cozy/cozy-drive#772]
On GNU/Linux, Cozy-drive interface doesn't show up when the tray icon is clicked. The only thing that appears with a left or right click is a popup menu with only one entry ("Quit").

Tested with Kubuntu 17.10
```
$ plasmashell --version
plasmashell 5.10.5
$ kf5-config --version
Qt : 5.9.1
Framework KDE : 5.38.0
kf5-config : 1.0
```

**Comment by y-lohse** [comment]
Hi @hleroy and thanks for the feedback!
This repo is for the Cozy Drive web-app, but I think you were looking for the [cozy-desktop repo](https://github.com/cozy-labs/cozy-desktop). I'll move this issue and #773 there, let me know if I misunderstood you and this was the correct repo after all!
