### ISSUE TITLE
[FEATURE] Close viewer modal when pressing the ESC key

### ISSUE THREAD

**Issue by moritzheiber** [cozy/cozy-drive#880]
I would love to be able to close the viewing modal on web/desktop for filetypes like images by pressing the `ESC` key. There already is navigation implemented for back and forth, i.e. scrolling through images, but there doesn't appear to be a shortcut for closing the viewer modal.

**Comment by y-lohse** [comment]
Hi @moritzheiber!
Thanks for the request, this has been implemented in #894 and should be part of the next release — presumably some time this week.

**Comment by moritzheiber** [comment]
Thanks!
